tests: create regression test suite of s3tests
aquarist-labs/s3gw-tools pull request #164
Opened 2022-09-08 07:56 UTC by m-ildefons

- Split out known-good s3tests for use as a regression test suite.

Since not all s3tests pass at the moment, the suite as a whole will always fail. This makes it unsuitable for use in a CI pipeline. To combat this, the known-good tests are split out into their own test suite to be used as regression tests in CI pipelines. The main use case for this is as merge criteria for PRs.

Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

2022-09-13 04:13 UTC, jecluis requested changes

2022-09-13 04:13 UTC, jecluis commented on tests/s3gw-s3tests-regression.sh
> +cat > test_cases <<EOF
can we dump this into a temp file and remove it on exit?

2022-09-13 04:13 UTC, jecluis commented on tests/s3gw-s3tests-regression.sh
> +git clone -b ceph-master https://github.com/ceph/s3-tests s3-tests.git || \
this, and the venv init below, should be conditional, lest we end up having problems because the directories already exist.

2022-09-13 04:13 UTC, jecluis commented on tests/s3gw-s3tests-regression.sh
> +display_name = testx$tenanteduser
`$tenantduser` doesn't seem defined anywhere?

2022-09-13 10:44 UTC, jecluis commented
@m-ildefons did we lose the test script on the latest push? Maybe you didn't stage it?

2022-09-13 10:45 UTC, jecluis commented
Oh, nevermind. I see what you did there, with https://github.com/aquarist-labs/ceph/pull/36 . Although I did find the script useful to be run manually :)

2022-09-13 12:32 UTC, m-ildefons commented on tests/s3gw-s3tests-regression.sh
> +cat > test_cases <<EOF
This whole code is copied from s3tests.sh. To avoid code duplication, avoid this rather ugly script around nosetests and generally cleaning things up much nicer, I have moved the script part into the workflow that will execute regression tests and just keep the config and the list of known-good tests.
Therefore the change request doesn't make much sense anymore in the context of the new version of this change.

2022-10-06 22:25 UTC, jecluis approved these changes
@m-ildefons good to merge

2022-10-10 13:40 UTC, merged