env/setup.sh: longhorn custom settings
aquarist-labs/s3gw-tools pull request #166
Opened 2022-09-08 16:02 UTC by torchiaf

- add possibility to define longhorn custom settings for k3s installation
- add longhorn-setting.yaml file

Fixes: https://github.com/aquarist-labs/s3gw/issues/96
Signed-off-by: Francesco Torchia <francesco.torchia@suse.com>

2022-09-09 06:53 UTC, votdev commented on env/setup.sh
> +  podman run --rm -i -e LONGHORN_SETTING="$(cat longhorn-setting.yaml)" -v "${PWD}":/workdir mikefarah/yq "$@"
Am I the only one who finds it disturbing to download a container to execute a CLI command? Times must have changed 😂

2022-09-09 06:59 UTC, votdev requested changes

2022-09-09 06:59 UTC, votdev commented on env/longhorn-setting.yaml
> +default-setting.yaml: |-
I would suggest to name this `env/longhorn-setting.yaml.sample`, add `env/longhorn-setting.yaml` to `.gitignore` and check for the existence of `env/longhorn-setting.yaml` in the script. Why that? Because every time you apply your custom settings to `env/longhorn-setting.yaml` git will interpret that as change and you will surely accidentally commit those changes.

2022-09-09 07:17 UTC, torchiaf commented on env/longhorn-setting.yaml
> +default-setting.yaml: |-
Totally agree!

2022-09-09 07:22 UTC, torchiaf commented on env/setup.sh
> +  podman run --rm -i -e LONGHORN_SETTING="$(cat longhorn-setting.yaml)" -v "${PWD}":/workdir mikefarah/yq "$@"
It's disturbing :joy: . Alternative is to install `yq` locally, I didn't want to introduce another step to the installation.

2022-09-09 07:54 UTC, votdev commented on env/setup.sh
> +  podman run --rm -i -e LONGHORN_SETTING="$(cat longhorn-setting.yaml)" -v "${PWD}":/workdir mikefarah/yq "$@"
It's ok to use a container here because i didn't find a PPA for Ubuntu to install this tool using the regular system package manager. I guess other OS do not have it in their repos too.

2022-09-09 08:39 UTC, votdev requested changes

2022-09-09 08:39 UTC, votdev commented on .gitignore
> +env/longhorn-setting.yaml
There is a separate `.gitignore` in the `env` directory. Please use this.

2022-09-09 08:40 UTC, votdev commented
Are you planning to update the documentation as well? If so, please add the PR link here, so the PRs are cross-linked.

2022-09-09 08:50 UTC, torchiaf commented
> Are you planning to update the documentation as well? If so, please add the PR link here, so the PRs are cross-linked.

Yes, I was waiting for this PR to be merged; I will link them.

2022-09-13 04:08 UTC, jecluis requested changes
haven't tested it, but it looks sound.

there's a potential line length problem that I'd like resolved before merge.

2022-09-13 04:08 UTC, jecluis commented on env/setup.sh
> +  podman run --rm -i -e LONGHORN_SETTING="$(cat longhorn-setting.yaml)" -v "${PWD}":/workdir mikefarah/yq "$@"
please ensure this line is wrapped at 80 columns.

2022-09-14 08:57 UTC, giubacc commented
Add these enhs in the CHANGELOG.md

2022-09-14 09:03 UTC, torchiaf commented on env/setup.sh
> +  podman run --rm -i -e LONGHORN_SETTING="$(cat longhorn-setting.yaml)" -v "${PWD}":/workdir mikefarah/yq "$@"
done.

2022-09-15 13:36 UTC, votdev commented on env/setup.sh
> +  if [[ ! -e "./longhorn-setting.yaml" ]]; then
Can we please get rid of bashism where it is not really necessary and support POSIX. I know we defined bash in the shebang, but do we really need bashism for a simple if clause? This will make it much more complicated to convert a script to be POSIX compatible if necessary. Note, in the Ubuntu/Debian world `dash` is the default shell. Check out https://mywiki.wooledge.org/Bashism.

2022-09-15 15:59 UTC, giubacc commented on CHANGELOG.md
> +## [0.6.0] - 2022-09-XX
better use the form `[unreleased]`

2022-09-16 10:44 UTC, torchiaf commented on env/setup.sh
> +  if [[ ! -e "./longhorn-setting.yaml" ]]; then
I read something about this topic and I also think it is worthwhile to use `dash`, but in this case should we edit whole `setup.sh` ? In case I can work on it.

2022-09-25 06:34 UTC, jecluis commented on env/setup.sh
> +  if [[ ! -e "./longhorn-setting.yaml" ]]; then
I don't have a particular opinion on bash vs dash vs whatever else (I use zsh as my default shell), but I don't see how this is an issue given the script explicitly uses bash, as defined by the shebang. Happy to be corrected and have an explanation on how this is an issue on systems where the default shell isn't bash though.

2022-09-26 08:36 UTC, votdev commented on env/setup.sh
> +  if [[ ! -e "./longhorn-setting.yaml" ]]; then
> Happy to be corrected and have an explanation on how this is an issue on systems where the default shell isn't bash though.

There isn't a problem in general. From my experience i find it problematic to use shell specific things when there are POSIX compliant alternatives.

2022-09-26 08:56 UTC, jecluis commented on env/setup.sh
> +  if [[ ! -e "./longhorn-setting.yaml" ]]; then
Don't take this as disregarding your experience because it's not meant as such. This is explicitly a bash script. It's expected to have bashisms. We can't be accounting for every alternative users choose to have to the interpreters we choose to use.

That said, I don't have a beef with this particular change; either way I'm fine.

2022-09-26 13:59 UTC, giubacc requested changes

2022-09-26 13:59 UTC, giubacc commented on CHANGELOG.md
> +## [0.5.0] - 2022-09-15
please, remove this line for `0.5.0`

2022-09-29 07:27 UTC, torchiaf commented on CHANGELOG.md
> +## [0.5.0] - 2022-09-15
done.

2022-09-29 07:31 UTC, merged