Fix misplaced entry on CHANGELOG.md
aquarist-labs/s3gw-tools pull request #187
Opened 2022-10-27 14:24 UTC by giubacc

Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

# Describe your changes

## Issue ticket number and link

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [x] CHANGELOG.md has been updated should there be relevant changes in this PR.

2022-10-27 14:49 UTC, votdev requested changes

2022-10-27 14:49 UTC, votdev commented on CHANGELOG.md
> +- build containers based on openSUSE Leap 15.4 instead of Tumbleweed.
```suggestion
- Build containers based on openSUSE Leap 15.4 instead of Tumbleweed.
```

2022-10-27 15:22 UTC, giubacc commented on CHANGELOG.md
> +- build containers based on openSUSE Leap 15.4 instead of Tumbleweed.
All previous entries begin lowercase; maybe it could be more correct fix Expose -> expose ?

2022-10-27 15:27 UTC, jecluis commented on CHANGELOG.md
> +- build containers based on openSUSE Leap 15.4 instead of Tumbleweed.
Please don't get caught up in those details. There will always be some entries in lowercase and others in uppercase. What matters is that they are there.

2022-10-27 15:28 UTC, jecluis approved these changes

2022-10-28 06:55 UTC, merged

2022-10-28 07:43 UTC, votdev commented on CHANGELOG.md
> +- build containers based on openSUSE Leap 15.4 instead of Tumbleweed.
If what we have done so far has been wrong, then we should not take this as an opportunity to continue doing it wrong. We should pay attention to correct spelling.

2022-10-28 07:49 UTC, giubacc commented on CHANGELOG.md
> +- build containers based on openSUSE Leap 15.4 instead of Tumbleweed.
Personally I totally agree on this; I would only do this on a separate PR, fixing all entries.
Given that the current convention (wrong or right) was to have all entries begin with a lowercase, I would say that the right thing to do is to keep that convention for consistency.
But I repeat, no problem if we want to change this.